# Generated by Django 4.1.2 on 2022-10-09 14:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Truancy',
            fields=[
                ('key', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(verbose_name='Дата')),
                ('all_people', models.IntegerField(verbose_name='Всего людей')),
                ('absenteeism', models.IntegerField(verbose_name='Количество отсутствующих')),
                ('num_pairs', models.IntegerField(verbose_name='Количество Пар')),
                ('num_hours', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Количество Часов')),
                ('percent', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Процент от общего числа')),
                ('Group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
