# Generated by Django 4.1.2 on 2022-10-09 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skip', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='truancy',
            old_name='Group',
            new_name='group',
        ),
    ]
