# Generated by Django 4.1.2 on 2022-10-19 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skip', '0003_truancyallgroup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='truancyallgroup',
            name='id',
        ),
        migrations.AlterField(
            model_name='truancyallgroup',
            name='date',
            field=models.DateField(primary_key=True, serialize=False),
        ),
    ]
