# Generated by Django 4.1.2 on 2022-10-22 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skip', '0006_rename_user_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
