# Generated by Django 4.1.3 on 2022-11-11 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skip', '0007_delete_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TruancyAllGroup',
        ),
    ]
